### ISSUE TITLE
ImportError: cannot import name 'polyglot_path' from 'polyglot' (E:\ProgramFiles\Python38\lib\site-packages\polyglot\__init__.py)

### ISSUE THREAD

**Issue by pythonlw** [riccardoFasan/polyglot#4]
Traceback (most recent call last):
  File "E:\ProgramFiles\Python38\lib\site-packages\polyglot\text.py", line 13, in <module>
    from polyglot.downloader import Downloader
  File "E:\ProgramFiles\Python38\lib\site-packages\polyglot\downloader.py", line 90, in <module>
    from polyglot import polyglot_path
ImportError: cannot import name 'polyglot_path' from 'polyglot' (E:\ProgramFiles\Python38\lib\site-packages\polyglot\__init__.py)

**Comment by riccardoFasan** [comment]
Please write more about your problem. I cannot reproduce it now.
